name: Continuous integration

on: 
  pull_request:
    branches:
      - main
  
permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  run-linting-unittests:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
          architecture: 'x64'

      - name: Display python version
        run: |
          import sys
          print(sys.version)
        shell: python

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Test with unittest
        env: 
          TEST_FILES: 'tests/*.py'
        run: |
          coverage run -m unittest $TEST_FILES -v
          coverage report
